name: ipv6 Test
on:
  workflow_dispatch:


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      
        

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}  # 👈 确保使用正确的分支
          token: ${{ secrets.GITHUB_TOKEN }}  # 👈 使用 GitHub Token 进行认证


      - name: Setup WARP
        uses: boywithkeyboard-archive/warp@v1.1.1
        with:
          onlyDoH: 'false'
          familyMode: 'off'

      
      - name: Run script
        run: | 
          ping6 -c 1 ipv6.google.com || echo "IPv6 not working"

      - name: Disconnect WARP
        if: always()
        run: |
          echo "Disconnecting WARP..."
          warp-cli disconnect || true
